/*
 * generated by Xtext 2.10.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CpnbStandaloneSetup extends CpnbStandaloneSetupGenerated {

	def static void doSetup() {
		new CpnbStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
